# Generated by Django 3.2.4 on 2021-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='headers',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
