# Generated by Django 3.2.4 on 2021-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20210814_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
