# Generated by Django 3.2.4 on 2021-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='data',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
