GET  http://127.0.0.1:8000/accounts/login HTTP/1.1
####

POST http://127.0.0.1:8000/webhooks/ HTTP/1.1
Content-Type: application/json


{
    "object": "page", 
    "entry": [
        {
            "id": "134150406795176", 
            "time": 1629115178, 
            "changes": [
                {
                    "value": 
                    {
                        "from": 
                        {
                            "id": "3438634522905232", 
                            "name": "Shemharos Swagar"
                        }, 
                        "post": 
                        {
                            "status_type": "mobile_status_update", 
                            "is_published": true, 
                            "updated_time": "2021-08-16T11:59:35+0000", 
                            "permalink_url": "https://www.facebook.com/syrianprof/posts/1732150443661823", 
                            "promotion_status": "ineligible", 
                            "id": "134150406795176_1732150443661823"}, 
                            "message": ".", 
                            "post_id": "134150406795176_1732150443661823", 
                            "comment_id": "1732150443661823_1732172883659579", 
                            "created_time": 1629115175, 
                            "item": "comment", 
                            "parent_id": "134150406795176_1732150443661823", 
                            "verb": "add"
                    }, 
                    "field": "feed"
                }
            ]
        }
    ]
}
