# Generated by Django 3.2.4 on 2021-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_automatepostcommentsresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatepostcommentsresponse',
            name='name',
        ),
        migrations.AddField(
            model_name='automatepostcommentsresponse',
            name='words',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
