# Generated by Django 3.2.4 on 2021-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210808_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatepostcommentsresponse',
            name='response_privetly',
        ),
        migrations.AddField(
            model_name='automatepostcommentsresponse',
            name='private_response',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
