# Generated by Django 3.2.4 on 2021-08-09 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatepostcommentsresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the reply', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
